// Opt-in RF-A05 regression on the audit pin. Never embeds third-party source.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { expect, it } from "vitest";
import { forceOccurrenceId, rosterId, selectionOccurrenceId } from "@rosterforge/roster-model";
import { prepareLocalCatalogueLibrary } from "./catalogue-library.js";
import { addLocalRosterChildSelection, addLocalRosterRootSelection, chooseLocalRosterChildGroupEntry, createLocalRosterSession, inspectLocalRosterChildChoices, localRosterRootChoices } from "./roster-session.js";
import { createUnitReferenceModel, referenceAttribution } from "./unit-reference-model.js";

const directory = process.env.ROSTERFORGE_BSDATA_JSON_DIR;
it.skipIf(!directory)("groups the audit's selected five and ten model Intercessor loadouts at the exact pin", async () => {
  if (!directory) throw new Error("Corpus not configured");
  expect(execFileSync("git", ["-c", `safe.directory=${resolve(directory).replaceAll("\\", "/")}`, "-C", directory, "rev-parse", "HEAD"], { encoding: "utf8" }).trim()).toBe("04c62fcd041b3808c39d5c46fd677c704027b979");
  const names = ["Imperium - Dark Angels.json", "Warhammer 40,000.json", "Imperium - Space Marines.json", "Imperium - Imperial Knights - Library.json", "Imperium - Agents of the Imperium.json", "Library - Titans.json", "Library - Astartes Heresy Legends.json", "Unaligned Forces.json"];
  const prepared = await prepareLocalCatalogueLibrary(names.map(filename => ({ filename, bytes: new Uint8Array(readFileSync(join(directory, filename))) })), { import: { batchId: "reference-corpus", importedAt: "2026-09-09T00:00:00Z" } });
  if (!prepared.ok) throw new Error("Import failed");
  const catalogue = prepared.value.selectableCatalogues.find(c => c.id === "470a-6daa-9014-12df")!;
  let n = 0;
  const next = () => selectionOccurrenceId(`ref-${++n}`);
  const created = createLocalRosterSession(catalogue, catalogue.context.forces.definitions.find(f => f.source.name === "Army Roster")!, { rosterId: rosterId("reference-roster"), forceId: forceOccurrenceId("reference-force"), name: "Reference QA", createSelectionId: next });
  if (!created.ok) throw new Error("Create failed");
  const unitId = next();
  const added = addLocalRosterRootSelection(created.value, localRosterRootChoices(catalogue).find(c => c.materialized.name === "Intercessor Squad")!, { selectionId: unitId, createSelectionId: next });
  if (!added.ok) throw new Error("Add failed");
  let session = added.value;
  const unit = () => session.roster.forces[0]!.selections.find(s => s.id === unitId)!;
  function addModel(name: string) {
    const choices = inspectLocalRosterChildChoices(session, unitId);
    if (!choices.ok) throw new Error("Inspect failed");
    const choice = choices.value.groups.flatMap(g => g.choices).find(c => c.name === name)!;
    const result = addLocalRosterChildSelection(session, unitId, choice, { selectionId: next(), createSelectionId: next });
    if (!result.ok) throw new Error("Model failed");
    session = result.value;
  }
  addModel("Intercessor"); addModel("Intercessor"); addModel("Intercessor"); addModel("Intercessor w/ Grenade Launcher");
  const sergeant = unit().selections.find(s => s.name === "Intercessor Sergeant")!;
  const choices = inspectLocalRosterChildChoices(session, sergeant.id);
  if (!choices.ok) throw new Error("Inspect failed");
  const group = choices.value.groups.find(g => g.choices.some(c => c.name === "Power fist"))!;
  const chosen = chooseLocalRosterChildGroupEntry(session, sergeant.id, group.group, group.choices.find(c => c.name === "Power fist")!, { selectionId: next(), createSelectionId: next });
  if (!chosen.ok) throw new Error("Loadout failed");
  session = chosen.value;
  const start = performance.now();
  const model = createUnitReferenceModel(session, unit());
  const coldMs = performance.now() - start;
  const warmStart = performance.now();
  createUnitReferenceModel(session, unit());
  const warmMs = performance.now() - warmStart;
  expect(model.profiles).toHaveLength(16);
  expect(model.profiles.filter(g => g.profile.value.typeName === "Unit").map(g => referenceAttribution(g.members))).toEqual(["1× Intercessor Sergeant", "3× Intercessor", "1× Intercessor w/ Grenade Launcher"]);
  expect(model.profiles.filter(g => g.profile.value.name?.includes("grenade launcher")).map(g => g.profile.value.name)).toEqual(["➤ Astartes grenade launcher - krak", "➤ Astartes grenade launcher - frag"]);
  expect(model.profiles.find(g => g.profile.value.name === "Power fist")?.members[0]?.label).toBe("Intercessor Sergeant");
  expect(model.rules.some(g => g.rule.value.name === "Templar Vows")).toBe(false);
  for (let i = 0; i < 5; i++) addModel("Intercessor");
  const largerStart = performance.now();
  const larger = createUnitReferenceModel(session, unit());
  expect(larger.profiles).toHaveLength(model.profiles.length);
  expect(larger.rules).toHaveLength(model.rules.length);
  expect(larger.profiles.filter(g => g.profile.value.typeName === "Unit").map(g => referenceAttribution(g.members))).toContain("8× Intercessor");
  console.info("RF-A05 projection measurements", { fiveColdMs: coldMs, fiveWarmMs: warmMs, tenColdMs: performance.now() - largerStart, profileGroups: model.profiles.length, ruleGroups: model.rules.length });
}, 120_000);
